version: "3"
services:
  app:
    build: 
        context: ./
        target: builder
    working_dir: /app
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
        - ./:/app:cached
